[global]
background_color = "#0F1723"
font.family = "Century gothic"
font.size = 48
font.color = "#002D56"

[home-score]
type = "number"
default = 0
position.x = 520
position.y = 25


[guest-score]
type = "number"
default = 0
position.x = 520
position.y = 102


[timer]
type = "timer"
rounding = "basketball"
default = "00:01:10"
position.x = 100
position.y = 180
keybind.start.key = "Space"
keybind.stop.key = "Z"

[home-label]
type = "label"
edit = true
default = "AOA"
position.x = 100
position.y = 25

[guest-label]
type = "label"
edit = true
default = "GUEST"
position.x = 100
position.y = 102

[sponsor-logo]
type = "image"
source = "background.png"
position.x = 0
position.y = 0
size.width = 640
size.height = 250
opacity = 1
