[global]
background_color = "#0F1723"
font.family = "Century gothic"
font.size = 48
font.color = "#002D56"

[home-score]
type = "number"
default = 0
position.x = 555
position.y = 55
alignment = "center"
keybind.increase.key = "A"
keybind.decrease.key = "B"
keybind.reset.key = "C"

[guest-score]
type = "number"
default = 0
position.x = 555
position.y = 132
alignment = "center"
keybind.increase.key = "D"
keybind.decrease.key = "E"
keybind.reset.key = "F"

[period-number]
type = "number"
default = 1
position.x = 425
position.y = 180
keybind.increase.key = "J"
keybind.decrease.key = "K"
keybind.reset.key = "N"

[timer]
type = "timer"
rounding = "basketball"
default = "00:01:10"
position.x = 100
position.y = 180
keybind.start.key = "G"
keybind.stop.key = "H"
keybind.increase.key = "L"
keybind.decrease.key = "M"
keybind.reset.key = "I"

[home-label]
type = "label"
edit = true
default = "AOA"
position.x = 100
position.y = 25

[guest-label]
type = "label"
edit = true
default = "GUEST"
position.x = 100
position.y = 102

[sponsor-logo]
type = "image"
source = "background.png"
position.x = 0
position.y = 0
size.width = 640
size.height = 250
opacity = 1
