[global]
background_color = "#0F1723"
font.family = "Century gothic"
font.size = 36
font.color = "#002D56"

[home-score]
type = "number"
default = 0
position.x = 36
position.y = 30


[guest-score]
type = "number"
default = 0
position.x = 36
position.y = 70


[timer]
type = "timer"
rounding = "basketball"
default = "00:01:10"
position.x = 250
position.y = 30
keybind.start.key = "Space"
keybind.stop.key = "Z"

[home-label]
type = "label"
edit = true
default = "AOA"
position.x = 470
position.y = 404
font.size = 28
font.color = "#D7E3EF"

[sponsor-logo]
type = "image"
source = "background.png"
position.x = 0
position.y = 0
size.width = 640
size.height = 250
opacity = 1
